[[people]]
blush = "ğŸ˜Š"
smirk = "ğŸ˜"
kissing_closed_eyes = "ğŸ˜š"
satisfied = "ğŸ˜†"
stuck_out_tongue_winking_eye = "ğŸ˜œ"
kissing = "ğŸ˜—"
sleeping = "ğŸ˜´"
anguished = "ğŸ˜§"
confused = "ğŸ˜•"
unamused = "ğŸ˜’"
disappointed_relieved = "ğŸ˜¥"
disappointed = "ğŸ˜"
cold_sweat = "ğŸ˜°"
sob = "ğŸ˜­"
scream = "ğŸ˜±"
angry = "ğŸ˜ "
sleepy = "ğŸ˜ª"
sunglasses = "ğŸ˜"
smiling_imp = "ğŸ˜ˆ"
innocent = "ğŸ˜‡"
blue_heart = "ğŸ’™"
green_heart = "ğŸ’š"
heartpulse = "ğŸ’—"
cupid = "ğŸ’˜"
star = "â­"
boom = "ğŸ’¥"
exclamation = "â—"
grey_question = "â”"
sweat_drops = "ğŸ’¦"
fire = "ğŸ”¥"
shit = "ğŸ’©"
-1 = "ğŸ‘"
punch = "ğŸ‘Š"
v = "âœŒï¸"
raised_hand = "âœ‹"
point_down = "ğŸ‘‡"
raised_hands = "ğŸ™Œ"
clap = "ğŸ‘"
fu = "ğŸ–•"
running = "ğŸƒ"
two_men_holding_hands = "ğŸ‘¬"
dancers = "ğŸ‘¯"
information_desk_person = "ğŸ’"
person_with_pouting_face = "ğŸ™"
couplekiss = "ğŸ’"
haircut = "ğŸ’‡"
girl = "ğŸ‘§"
baby = "ğŸ‘¶"
person_with_blond_hair = "ğŸ‘±"
construction_worker = "ğŸ‘·"
princess = "ğŸ‘¸"
heart_eyes_cat = "ğŸ˜»"
scream_cat = "ğŸ™€"
pouting_cat = "ğŸ˜¾"
see_no_evil = "ğŸ™ˆ"
guardsman = "ğŸ’‚â€â™‚ï¸"
lips = "ğŸ‘„"
ear = "ğŸ‘‚"
tongue = "ğŸ‘…"
busts_in_silhouette = "ğŸ‘¥"
smile = "ğŸ˜„"
smiley = "ğŸ˜ƒ"
heart_eyes = "ğŸ˜"
flushed = "ğŸ˜³"
grin = "ğŸ˜"
stuck_out_tongue_closed_eyes = "ğŸ˜"
kissing_smiling_eyes = "ğŸ˜™"
worried = "ğŸ˜Ÿ"
open_mouth = "ğŸ˜®"
hushed = "ğŸ˜¯"
sweat_smile = "ğŸ˜…"
weary = "ğŸ˜©"
confounded = "ğŸ˜–"
persevere = "ğŸ˜£"
joy = "ğŸ˜‚"
rage = "ğŸ˜¡"
yum = "ğŸ˜‹"
dizzy_face = "ğŸ˜µ"
neutral_face = "ğŸ˜"
alien = "ğŸ‘½"
purple_heart = "ğŸ’œ"
broken_heart = "ğŸ’”"
two_hearts = "ğŸ’•"
sparkling_heart = "ğŸ’–"
star2 = "ğŸŒŸ"
collision = "ğŸ’¥"
question = "â“"
zzz = "ğŸ’¤"
notes = "ğŸ¶"
hankey = "ğŸ’©"
plus_1 = "ğŸ‘"
thumbsdown = "ğŸ‘"
facepunch = "ğŸ‘Š"
wave = "ğŸ‘‹"
open_hands = "ğŸ‘"
point_left = "ğŸ‘ˆ"
pray = "ğŸ™"
muscle = "ğŸ’ª"
walking = "ğŸš¶"
couple = "ğŸ‘«"
two_women_holding_hands = "ğŸ‘­"
ok_woman = "ğŸ™†â€â™€ï¸"
raising_hand = "ğŸ™‹"
person_frowning = "ğŸ™"
couple_with_heart = "ğŸ’‘"
nail_care = "ğŸ’…"
woman = "ğŸ‘©"
older_woman = "ğŸ‘µ"
man_with_gua_pi_mao = "ğŸ‘²"
cop = "ğŸ‘®"
smiley_cat = "ğŸ˜º"
kissing_cat = "ğŸ˜½"
crying_cat_face = "ğŸ˜¿"
japanese_ogre = "ğŸ‘¹"
hear_no_evil = "ğŸ™‰"
skull = "ğŸ’€"
kiss = "ğŸ’‹"
eyes = "ğŸ‘€"
love_letter = "ğŸ’Œ"
speech_balloon = "ğŸ’¬"
laughing = "ğŸ˜†"
relaxed = "â˜ºï¸"
kissing_heart = "ğŸ˜˜"
relieved = "ğŸ˜Œ"
wink = "ğŸ˜‰"
grinning = "ğŸ˜€"
stuck_out_tongue = "ğŸ˜›"
frowning = "ğŸ˜¦"
grimacing = "ğŸ˜¬"
expressionless = "ğŸ˜‘"
sweat = "ğŸ˜“"
pensive = "ğŸ˜”"
fearful = "ğŸ˜¨"
cry = "ğŸ˜¢"
astonished = "ğŸ˜²"
tired_face = "ğŸ˜«"
triumph = "ğŸ˜¤"
mask = "ğŸ˜·"
imp = "ğŸ‘¿"
no_mouth = "ğŸ˜¶"
yellow_heart = "ğŸ’›"
heart = "â¤ï¸"
heartbeat = "ğŸ’“"
revolving_hearts = "ğŸ’"
sparkles = "âœ¨"
dizzy = "ğŸ’«"
anger = "ğŸ’¢"
grey_exclamation = "â•"
dash = "ğŸ’¨"
musical_note = "ğŸµ"
poop = "ğŸ’©"
thumbsup = "ğŸ‘"
ok_hand = "ğŸ‘Œ"
fist = "âœŠ"
hand = "âœ‹"
point_up = "â˜ï¸"
point_right = "ğŸ‘‰"
point_up_2 = "ğŸ‘†"
metal = "ğŸ¤˜"
runner = "ğŸƒ"
family = "ğŸ‘ª"
dancer = "ğŸ’ƒ"
no_good = "ğŸ™…"
bride_with_veil = "ğŸ‘°â€â™€ï¸"
bow = "ğŸ™‡"
massage = "ğŸ’†"
boy = "ğŸ‘¦"
man = "ğŸ‘¨"
older_man = "ğŸ‘´"
man_with_turban = "ğŸ‘³â€â™‚ï¸"
angel = "ğŸ‘¼"
smile_cat = "ğŸ˜¸"
smirk_cat = "ğŸ˜¼"
joy_cat = "ğŸ˜¹"
japanese_goblin = "ğŸ‘º"
speak_no_evil = "ğŸ™Š"
feet = "ğŸ¾"
droplet = "ğŸ’§"
nose = "ğŸ‘ƒ"
bust_in_silhouette = "ğŸ‘¤"
thought_balloon = "ğŸ’­"

[[nature]]
snowflake = "â„ï¸"
cyclone = "ğŸŒ€"
cat = "ğŸ±"
hamster = "ğŸ¹"
frog = "ğŸ¸"
bear = "ğŸ»"
cow = "ğŸ®"
monkey = "ğŸ’"
camel = "ğŸ«"
panda_face = "ğŸ¼"
baby_chick = "ğŸ¤"
chicken = "ğŸ”"
bug = "ğŸ›"
beetle = "ğŸª²"
tropical_fish = "ğŸ "
whale2 = "ğŸ‹"
ram = "ğŸ"
tiger2 = "ğŸ…"
goat = "ğŸ"
pig2 = "ğŸ–"
dragon_face = "ğŸ²"
dromedary_camel = "ğŸª"
poodle = "ğŸ©"
cherry_blossom = "ğŸŒ¸"
rose = "ğŸŒ¹"
maple_leaf = "ğŸ"
herb = "ğŸŒ¿"
palm_tree = "ğŸŒ´"
chestnut = "ğŸŒ°"
ear_of_rice = "ğŸŒ¾"
sun_with_face = "ğŸŒ"
new_moon = "ğŸŒ‘"
waxing_gibbous_moon = "ğŸŒ”"
last_quarter_moon = "ğŸŒ—"
first_quarter_moon_with_face = "ğŸŒ›"
earth_americas = "ğŸŒ"
milky_way = "ğŸŒŒ"
umbrella = "â˜”"
snowman = "â›„"
foggy = "ğŸŒ"
dog = "ğŸ¶"
rabbit = "ğŸ°"
tiger = "ğŸ¯"
pig = "ğŸ·"
boar = "ğŸ—"
horse = "ğŸ´"
sheep = "ğŸ‘"
snake = "ğŸ"
hatched_chick = "ğŸ¥"
penguin = "ğŸ§"
honeybee = "ğŸ"
snail = "ğŸŒ"
fish = "ğŸŸ"
dolphin = "ğŸ¬"
rat = "ğŸ€"
rabbit2 = "ğŸ‡"
rooster = "ğŸ“"
mouse2 = "ğŸ"
blowfish = "ğŸ¡"
leopard = "ğŸ†"
paw_prints = "ğŸ¾"
tulip = "ğŸŒ·"
sunflower = "ğŸŒ»"
leaves = "ğŸƒ"
mushroom = "ğŸ„"
evergreen_tree = "ğŸŒ²"
seedling = "ğŸŒ±"
shell = "ğŸš"
full_moon_with_face = "ğŸŒ"
waxing_crescent_moon = "ğŸŒ’"
full_moon = "ğŸŒ•"
waning_crescent_moon = "ğŸŒ˜"
moon = "ğŸŒ”"
earth_asia = "ğŸŒ"
partly_sunny = "â›…"
cloud = "â˜ï¸"
zap = "âš¡"
ocean = "ğŸŒŠ"
mouse = "ğŸ­"
wolf = "ğŸº"
koala = "ğŸ¨"
pig_nose = "ğŸ½"
monkey_face = "ğŸµ"
racehorse = "ğŸ"
elephant = "ğŸ˜"
bird = "ğŸ¦"
hatching_chick = "ğŸ£"
turtle = "ğŸ¢"
ant = "ğŸœ"
octopus = "ğŸ™"
whale = "ğŸ³"
cow2 = "ğŸ„"
water_buffalo = "ğŸƒ"
dragon = "ğŸ‰"
dog2 = "ğŸ•"
ox = "ğŸ‚"
crocodile = "ğŸŠ"
cat2 = "ğŸˆ"
bouquet = "ğŸ’"
four_leaf_clover = "ğŸ€"
hibiscus = "ğŸŒº"
fallen_leaf = "ğŸ‚"
cactus = "ğŸŒµ"
deciduous_tree = "ğŸŒ³"
blossom = "ğŸŒ¼"
globe_with_meridians = "ğŸŒ"
new_moon_with_face = "ğŸŒš"
first_quarter_moon = "ğŸŒ“"
waning_gibbous_moon = "ğŸŒ–"
last_quarter_moon_with_face = "ğŸŒœ"
earth_africa = "ğŸŒ"
volcano = "ğŸŒ‹"

[[objects]]
bamboo = "ğŸ"
school_satchel = "ğŸ’"
fireworks = "ğŸ†"
rice_scene = "ğŸ‘"
santa = "ğŸ…"
bell = "ğŸ””"
tada = "ğŸ‰"
crystal_ball = "ğŸ”®"
floppy_disk = "ğŸ’¾"
movie_camera = "ğŸ¥"
iphone = "ğŸ“±"
telephone_receiver = "ğŸ“"
minidisc = "ğŸ’½"
speaker = "ğŸ”ˆ"
mega = "ğŸ“£"
alarm_clock = "â°"
satellite = "ğŸ“¡"
mag_right = "ğŸ”"
lock_with_ink_pen = "ğŸ”"
bulb = "ğŸ’¡"
low_brightness = "ğŸ”…"
calling = "ğŸ“²"
postbox = "ğŸ“®"
shower = "ğŸš¿"
nut_and_bolt = "ğŸ”©"
moneybag = "ğŸ’°"
pound = "ğŸ’·"
money_with_wings = "ğŸ’¸"
outbox_tray = "ğŸ“¤"
postal_horn = "ğŸ“¯"
mailbox_with_no_mail = "ğŸ“­"
bomb = "ğŸ’£"
pill = "ğŸ’Š"
page_with_curl = "ğŸ“ƒ"
chart_with_upwards_trend = "ğŸ“ˆ"
clipboard = "ğŸ“‹"
card_index = "ğŸ“‡"
scissors = "âœ‚ï¸"
black_nib = "âœ’ï¸"
triangular_ruler = "ğŸ“"
blue_book = "ğŸ“˜"
notebook_with_decorative_cover = "ğŸ“”"
bookmark = "ğŸ”–"
telescope = "ğŸ”­"
basketball = "ğŸ€"
tennis = "ğŸ¾"
bowling = "ğŸ³"
bicyclist = "ğŸš´"
swimmer = "ğŸŠ"
spades = "â™ ï¸"
diamonds = "â™¦ï¸"
trophy = "ğŸ†"
violin = "ğŸ»"
black_joker = "ğŸƒ"
dart = "ğŸ¯"
memo = "ğŸ“"
art = "ğŸ¨"
trumpet = "ğŸº"
shoe = "ğŸ‘"
lipstick = "ğŸ’„"
tshirt = "ğŸ‘•"
dress = "ğŸ‘—"
kimono = "ğŸ‘˜"
tophat = "ğŸ©"
mans_shoe = "ğŸ‘"
handbag = "ğŸ‘œ"
eyeglasses = "ğŸ‘“"
tea = "ğŸµ"
beer = "ğŸº"
tropical_drink = "ğŸ¹"
pizza = "ğŸ•"
poultry_leg = "ğŸ—"
curry = "ğŸ›"
sushi = "ğŸ£"
rice_cracker = "ğŸ˜"
stew = "ğŸ²"
egg = "ğŸ¥š"
custard = "ğŸ®"
shaved_ice = "ğŸ§"
cookie = "ğŸª"
lollipop = "ğŸ­"
green_apple = "ğŸ"
cherries = "ğŸ’"
strawberry = "ğŸ“"
banana = "ğŸŒ"
sweet_potato = "ğŸ "
corn = "ğŸŒ½"
gift_heart = "ğŸ’"
mortar_board = "ğŸ“"
sparkler = "ğŸ‡"
jack_o_lantern = "ğŸƒ"
christmas_tree = "ğŸ„"
no_bell = "ğŸ”•"
confetti_ball = "ğŸŠ"
cd = "ğŸ’¿"
camera = "ğŸ“·"
computer = "ğŸ’»"
phone = "â˜ï¸"
pager = "ğŸ“Ÿ"
vhs = "ğŸ“¼"
mute = "ğŸ”‡"
hourglass = "âŒ›"
watch = "âŒš"
loop = "â¿"
unlock = "ğŸ”“"
closed_lock_with_key = "ğŸ”"
flashlight = "ğŸ”¦"
electric_plug = "ğŸ”Œ"
email = "ğŸ“§"
bath = "ğŸ›€"
toilet = "ğŸš½"
hammer = "ğŸ”¨"
yen = "ğŸ’´"
euro = "ğŸ’¶"
e-mail = "ğŸ“§"
envelope = "âœ‰ï¸"
mailbox_closed = "ğŸ“ª"
door = "ğŸšª"
gun = "ğŸ”«"
syringe = "ğŸ’‰"
bookmark_tabs = "ğŸ“‘"
chart_with_downwards_trend = "ğŸ“‰"
calendar = "ğŸ“†"
file_folder = "ğŸ“"
pushpin = "ğŸ“Œ"
pencil2 = "âœï¸"
closed_book = "ğŸ“•"
orange_book = "ğŸ“™"
ledger = "ğŸ“’"
name_badge = "ğŸ“›"
newspaper = "ğŸ“°"
soccer = "âš½"
8ball = "ğŸ±"
golf = "â›³"
horse_racing = "ğŸ‡"
surfer = "ğŸ„"
hearts = "â™¥ï¸"
gem = "ğŸ’"
musical_score = "ğŸ¼"
space_invader = "ğŸ‘¾"
flower_playing_cards = "ğŸ´"
mahjong = "ğŸ€„"
pencil = "ğŸ“"
microphone = "ğŸ¤"
saxophone = "ğŸ·"
sandal = "ğŸ‘¡"
boot = "ğŸ‘¢"
necktie = "ğŸ‘”"
running_shirt_with_sash = "ğŸ½"
bikini = "ğŸ‘™"
crown = "ğŸ‘‘"
closed_umbrella = "ğŸŒ‚"
pouch = "ğŸ‘"
fishing_pole_and_fish = "ğŸ£"
sake = "ğŸ¶"
beers = "ğŸ»"
wine_glass = "ğŸ·"
hamburger = "ğŸ”"
meat_on_bone = "ğŸ–"
fried_shrimp = "ğŸ¤"
fish_cake = "ğŸ¥"
rice = "ğŸš"
oden = "ğŸ¢"
bread = "ğŸ"
icecream = "ğŸ¦"
birthday = "ğŸ‚"
chocolate_bar = "ğŸ«"
honey_pot = "ğŸ¯"
tangerine = "ğŸŠ"
grapes = "ğŸ‡"
peach = "ğŸ‘"
pear = "ğŸ"
eggplant = "ğŸ†"
dolls = "ğŸ"
flags = "ğŸ"
wind_chime = "ğŸ"
ghost = "ğŸ‘»"
gift = "ğŸ"
tanabata_tree = "ğŸ‹"
balloon = "ğŸˆ"
dvd = "ğŸ“€"
video_camera = "ğŸ“¹"
tv = "ğŸ“º"
telephone = "â˜ï¸"
fax = "ğŸ“ "
sound = "ğŸ”‰"
loudspeaker = "ğŸ“¢"
hourglass_flowing_sand = "â³"
radio = "ğŸ“»"
mag = "ğŸ”"
lock = "ğŸ”’"
key = "ğŸ”‘"
high_brightness = "ğŸ”†"
battery = "ğŸ”‹"
mailbox = "ğŸ“«"
bathtub = "ğŸ›"
wrench = "ğŸ”§"
seat = "ğŸ’º"
dollar = "ğŸ’µ"
credit_card = "ğŸ’³"
inbox_tray = "ğŸ“¥"
incoming_envelope = "ğŸ“¨"
mailbox_with_mail = "ğŸ“¬"
smoking = "ğŸš¬"
hocho = "ğŸ”ª"
page_facing_up = "ğŸ“„"
bar_chart = "ğŸ“Š"
scroll = "ğŸ“œ"
date = "ğŸ“…"
open_file_folder = "ğŸ“‚"
paperclip = "ğŸ“"
straight_ruler = "ğŸ“"
green_book = "ğŸ“—"
notebook = "ğŸ““"
books = "ğŸ“š"
microscope = "ğŸ”¬"
football = "ğŸˆ"
baseball = "âš¾"
rugby_football = "ğŸ‰"
mountain_bicyclist = "ğŸšµ"
snowboarder = "ğŸ‚"
ski = "ğŸ¿"
clubs = "â™£ï¸"
ring = "ğŸ’"
musical_keyboard = "ğŸ¹"
video_game = "ğŸ®"
game_die = "ğŸ²"
clapper = "ğŸ¬"
book = "ğŸ“–"
headphones = "ğŸ§"
guitar = "ğŸ¸"
high_heel = "ğŸ‘ "
shirt = "ğŸ‘•"
womans_clothes = "ğŸ‘š"
jeans = "ğŸ‘–"
ribbon = "ğŸ€"
womans_hat = "ğŸ‘’"
briefcase = "ğŸ’¼"
purse = "ğŸ‘›"
coffee = "â˜•"
baby_bottle = "ğŸ¼"
cocktail = "ğŸ¸"
fork_and_knife = "ğŸ´"
fries = "ğŸŸ"
spaghetti = "ğŸ"
bento = "ğŸ±"
rice_ball = "ğŸ™"
ramen = "ğŸœ"
dango = "ğŸ¡"
doughnut = "ğŸ©"
ice_cream = "ğŸ¨"
cake = "ğŸ°"
candy = "ğŸ¬"
apple = "ğŸ"
lemon = "ğŸ‹"
watermelon = "ğŸ‰"
melon = "ğŸˆ"
pineapple = "ğŸ"
tomato = "ğŸ…"

[[places]]
house = "ğŸ "
office = "ğŸ¢"
bank = "ğŸ¦"
hotel = "ğŸ¨"
department_store = "ğŸ¬"
city_sunset = "ğŸŒ†"
tent = "â›º"
japan = "ğŸ—¾"
sunrise = "ğŸŒ…"
bridge_at_night = "ğŸŒ‰"
ferris_wheel = "ğŸ¡"
ship = "ğŸš¢"
sailboat = "â›µ"
rocket = "ğŸš€"
steam_locomotive = "ğŸš‚"
bike = "ğŸš²"
mountain_cableway = "ğŸš "
oncoming_automobile = "ğŸš˜"
taxi = "ğŸš•"
bus = "ğŸšŒ"
police_car = "ğŸš“"
ambulance = "ğŸš‘"
train = "ğŸš‹"
bullettrain_front = "ğŸš…"
monorail = "ğŸš"
ticket = "ğŸ«"
traffic_light = "ğŸš¥"
beginner = "ğŸ”°"
busstop = "ğŸš"
checkered_flag = "ğŸ"
moyai = "ğŸ—¿"
round_pushpin = "ğŸ“"
kr = "ğŸ‡°ğŸ‡·"
fr = "ğŸ‡«ğŸ‡·"
ru = "ğŸ‡·ğŸ‡º"
de = "ğŸ‡©ğŸ‡ª"
house_with_garden = "ğŸ¡"
post_office = "ğŸ£"
convenience_store = "ğŸª"
wedding = "ğŸ’’"
european_post_office = "ğŸ¤"
japanese_castle = "ğŸ¯"
factory = "ğŸ­"
mount_fuji = "ğŸ—»"
stars = "ğŸŒ "
carousel_horse = "ğŸ "
fountain = "â›²"
speedboat = "ğŸš¤"
rowboat = "ğŸš£"
airplane = "âœˆï¸"
tram = "ğŸšŠ"
aerial_tramway = "ğŸš¡"
tractor = "ğŸšœ"
car = "ğŸš—"
oncoming_taxi = "ğŸš–"
oncoming_bus = "ğŸš"
oncoming_police_car = "ğŸš”"
minibus = "ğŸš"
station = "ğŸš‰"
bullettrain_side = "ğŸš„"
railway_car = "ğŸšƒ"
fuelpump = "â›½"
warning = "âš ï¸"
atm = "ğŸ§"
barber = "ğŸ’ˆ"
crossed_flags = "ğŸŒ"
circus_tent = "ğŸª"
triangular_flag_on_post = "ğŸš©"
cn = "ğŸ‡¨ğŸ‡³"
es = "ğŸ‡ªğŸ‡¸"
gb = "ğŸ‡¬ğŸ‡§"
school = "ğŸ«"
hospital = "ğŸ¥"
love_hotel = "ğŸ©"
church = "â›ª"
city_sunrise = "ğŸŒ‡"
european_castle = "ğŸ°"
tokyo_tower = "ğŸ—¼"
sunrise_over_mountains = "ğŸŒ„"
statue_of_liberty = "ğŸ—½"
rainbow = "ğŸŒˆ"
roller_coaster = "ğŸ¢"
boat = "â›µ"
anchor = "âš“"
helicopter = "ğŸš"
mountain_railway = "ğŸš"
suspension_railway = "ğŸšŸ"
blue_car = "ğŸš™"
red_car = "ğŸš—"
articulated_lorry = "ğŸš›"
rotating_light = "ğŸš¨"
fire_engine = "ğŸš’"
truck = "ğŸšš"
train2 = "ğŸš†"
light_rail = "ğŸšˆ"
trolleybus = "ğŸš"
vertical_traffic_light = "ğŸš¦"
construction = "ğŸš§"
slot_machine = "ğŸ°"
hotsprings = "â™¨ï¸"
izakaya_lantern = "ğŸ®"
performing_arts = "ğŸ­"
jp = "ğŸ‡¯ğŸ‡µ"
us = "ğŸ‡ºğŸ‡¸"
it = "ğŸ‡®ğŸ‡¹"
uk = "ğŸ‡¬ğŸ‡§"

[[symbols]]
one = "1ï¸âƒ£"
four = "4ï¸âƒ£"
seven = "7ï¸âƒ£"
keycap_ten = "ğŸ”Ÿ"
hash = "#ï¸âƒ£"
arrow_down = "â¬‡ï¸"
capital_abcd = "ğŸ” "
arrow_lower_left = "â†™ï¸"
arrow_up = "â¬†ï¸"
arrow_double_down = "â¬"
arrow_heading_down = "â¤µï¸"
arrow_right_hook = "â†ªï¸"
arrow_up_small = "ğŸ”¼"
rewind = "âª"
ok = "ğŸ†—"
repeat_one = "ğŸ”‚"
up = "ğŸ†™"
ng = "ğŸ†–"
signal_strength = "ğŸ“¶"
u55b6 = "ğŸˆº"
u6709 = "ğŸˆ¶"
u7533 = "ğŸˆ¸"
sa = "ğŸˆ‚ï¸"
womens = "ğŸšº"
parking = "ğŸ…¿ï¸"
baggage_claim = "ğŸ›„"
potable_water = "ğŸš°"
congratulations = "ãŠ—ï¸"
left_luggage = "ğŸ›…"
cl = "ğŸ†‘"
no_entry_sign = "ğŸš«"
do_not_litter = "ğŸš¯"
no_pedestrians = "ğŸš·"
eight_spoked_asterisk = "âœ³ï¸"
vs = "ğŸ†š"
chart = "ğŸ’¹"
taurus = "â™‰"
leo = "â™Œ"
scorpius = "â™"
aquarius = "â™’"
six_pointed_star = "ğŸ”¯"
b = "ğŸ…±ï¸"
diamond_shape_with_a_dot_inside = "ğŸ’ "
on = "ğŸ”›"
clock130 = "ğŸ•œ"
clock11 = "ğŸ•š"
clock1230 = "ğŸ•§"
clock3 = "ğŸ•’"
clock430 = "ğŸ•Ÿ"
clock6 = "ğŸ••"
clock730 = "ğŸ•¢"
clock9 = "ğŸ•˜"
copyright = "Â©ï¸"
x = "âŒ"
interrobang = "â‰ï¸"
heavy_plus_sign = "â•"
white_flower = "ğŸ’®"
ballot_box_with_check = "â˜‘ï¸"
curly_loop = "â°"
trident = "ğŸ”±"
white_check_mark = "âœ…"
black_circle = "âš«"
large_blue_circle = "ğŸ”µ"
small_blue_diamond = "ğŸ”¹"
small_red_triangle_down = "ğŸ”»"
two = "2ï¸âƒ£"
five = "5ï¸âƒ£"
eight = "8ï¸âƒ£"
1234 = "ğŸ”¢"
block_symbols = "ğŸ”£"
arrow_forward = "â–¶ï¸"
abcd = "ğŸ”¡"
arrow_lower_right = "â†˜ï¸"
arrow_upper_left = "â†–ï¸"
arrow_double_up = "â«"
arrow_heading_up = "â¤´ï¸"
left_right_arrow = "â†”ï¸"
arrows_clockwise = "ğŸ”ƒ"
fast_forward = "â©"
twisted_rightwards_arrows = "ğŸ”€"
new = "ğŸ†•"
cool = "ğŸ†’"
cinema = "ğŸ¦"
u5272 = "ğŸˆ¹"
u6307 = "ğŸˆ¯"
u6e80 = "ğŸˆµ"
u7a7a = "ğŸˆ³"
restroom = "ğŸš»"
baby_symbol = "ğŸš¼"
wheelchair = "â™¿"
accept = "ğŸ‰‘"
put_litter_in_its_place = "ğŸš®"
m = "â“‚ï¸"
customs = "ğŸ›ƒ"
sos = "ğŸ†˜"
underage = "ğŸ”"
non-potable_water = "ğŸš±"
children_crossing = "ğŸš¸"
eight_pointed_black_star = "âœ´ï¸"
vibration_mode = "ğŸ“³"
currency_exchange = "ğŸ’±"
gemini = "â™Š"
virgo = "â™"
sagittarius = "â™"
pisces = "â™“"
negative_squared_cross_mark = "â"
ab = "ğŸ†"
recycle = "â™»ï¸"
soon = "ğŸ”œ"
clock10 = "ğŸ•™"
clock1130 = "ğŸ•¦"
clock2 = "ğŸ•‘"
clock330 = "ğŸ•"
clock5 = "ğŸ•”"
clock630 = "ğŸ•¡"
clock8 = "ğŸ•—"
clock930 = "ğŸ•¤"
registered = "Â®ï¸"
heavy_exclamation_mark = "â—"
o = "â­•"
heavy_minus_sign = "â–"
100 = "ğŸ’¯"
radio_button = "ğŸ”˜"
wavy_dash = "ã€°ï¸"
black_square = "black_square"
black_square_button = "ğŸ”²"
white_circle = "âšª"
large_blue_diamond = "ğŸ”·"
small_orange_diamond = "ğŸ”¸"
three = "3ï¸âƒ£"
six = "6ï¸âƒ£"
nine = "9ï¸âƒ£"
zero = "0ï¸âƒ£"
arrow_backward = "â—€ï¸"
arrow_left = "â¬…ï¸"
abc = "ğŸ”¤"
arrow_right = "â¡ï¸"
arrow_upper_right = "â†—ï¸"
arrow_down_small = "ğŸ”½"
leftwards_arrow_with_hook = "â†©ï¸"
arrow_up_down = "â†•ï¸"
arrows_counterclockwise = "ğŸ”„"
information_source = "â„¹ï¸"
repeat = "ğŸ”"
top = "ğŸ”"
free = "ğŸ†“"
koko = "ğŸˆ"
u5408 = "ğŸˆ´"
u6708 = "ğŸˆ·ï¸"
u7121 = "ğŸˆš"
u7981 = "ğŸˆ²"
mens = "ğŸš¹"
no_smoking = "ğŸš­"
metro = "ğŸš‡"
wc = "ğŸš¾"
secret = "ãŠ™ï¸"
passport_control = "ğŸ›‚"
ideograph_advantage = "ğŸ‰"
id = "ğŸ†”"
no_mobile_phones = "ğŸ“µ"
no_bicycles = "ğŸš³"
no_entry = "â›”"
heart_decoration = "ğŸ’Ÿ"
mobile_phone_off = "ğŸ“´"
aries = "â™ˆ"
cancer = "â™‹"
libra = "â™"
capricorn = "â™‘"
ophiuchus = "â›"
a = "ğŸ…°ï¸"
o2 = "ğŸ…¾ï¸"
end = "ğŸ”š"
clock1 = "ğŸ•"
clock1030 = "ğŸ•¥"
clock12 = "ğŸ•›"
clock230 = "ğŸ•"
clock4 = "ğŸ•“"
clock530 = "ğŸ• "
clock7 = "ğŸ•–"
clock830 = "ğŸ•£"
heavy_dollar_sign = "ğŸ’²"
tm = "â„¢ï¸"
bangbang = "â€¼ï¸"
heavy_multiplication_x = "âœ–ï¸"
heavy_division_sign = "â—"
heavy_check_mark = "âœ”ï¸"
link = "ğŸ”—"
part_alternation_mark = "ã€½ï¸"
white_square = "white_square"
white_square_button = "ğŸ”³"
red_circle = "ğŸ”´"
large_orange_diamond = "ğŸ”¶"
small_red_triangle = "ğŸ”º"