name: Build Windows

on:
  push:
    branches:
      - "!*"
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on:
      labels: windows-latest-8-cores

    permissions:
      contents: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Get rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.73.0
          target: x86_64-pc-windows-msvc
          override: true

      - name: Install Wix
        uses: actions/checkout@v2
        with:
          repository: fbarresi/wix
          path: wix

      - name: Install cargo wix
        run: cargo install cargo-wix

      - name: Install FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: Build Uplink
        run: cargo build --release -F production_mode
      
      - name: Build Installer 
        run: cargo wix --package uplink --no-build --nocapture
        
      - name: Sign Windows Installer
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.WINDOWS_CERTIFICATE }}'
          password: '${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}'
          folder: 'target/wix'
          recursive: true
          files: |
            target/wix/*.msi

      - name: Github Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/wix/*.msi