name: Add new ticket label on issues
on:
  issues:
    types: [opened]

jobs:
  add-label:
    name: Add Label - new ticket added
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christianvuerings/add-labels@v1
        with:
          labels: |
            New Ticket
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
